---
name: oasys
on:
  push:
    branches:
      - main
    paths:
      - 'terraform/environments/oasys/**'
      - '.github/workflows/oasys.yml'

  pull_request:
    branches:
      - main
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'terraform/environments/oasys/**'
      - '.github/workflows/oasys.yml'

  workflow_dispatch:
    inputs:
      action:
        description: 'Set either [deploy|destroy].'
        default: 'deploy'
        required: true
        type: string
        options:
          - deploy
          - destroy

permissions:
  id-token: write  # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:

  deletes3:
    name: "deletes3"
    runs-on: ubuntu-latest
    steps:
      - name: deletes3
        run: |
          aws s3api delete-objects --bucket t1-oasys-internal-lb-access-logs20230421120108986200000002 --delete "$(aws s3api list-object-versions --bucket t1-oasys-internal-lb-access-logs20230421120108986200000002 | jq '{Objects: [.Versions[] | {Key:.Key, VersionId : .VersionId}], Quiet: false}')"
          aws s3api delete-objects --bucket t2-oasys-internal-lb-access-logs20230414165431346600000003 --delete "$(aws s3api list-object-versions --bucket t2-oasys-internal-lb-access-logs20230414165431346600000003 | jq '{Objects: [.Versions[] | {Key:.Key, VersionId : .VersionId}], Quiet: false}')"    

  strategy:
    uses: ./.github/workflows/reusable_terraform_strategy.yml
    if: inputs.action != 'destroy'
    with:
      application: "${{ github.workflow }}"

  terraform:
    needs: strategy
    if: inputs.action != 'destroy'
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.strategy.outputs.matrix) }}
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      application: "${{ github.workflow }}"
      environment: "${{ matrix.target }}"
      action: "${{ matrix.action }}"
    secrets:
      modernisation_platform_environments: "${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}"
      pipeline_github_token: "${{ secrets.MODERNISATION_PLATFORM_CI_USER_ENVIRONMENTS_REPO_PAT }}"

  destroy-development:
    if: inputs.action == 'destroy'
    uses: ./.github/workflows/reusable_terraform_plan_apply.yml
    with:
      application: "${{ github.workflow }}"
      environment: "development"
      action: "plan_apply"
      plan_apply_tfargs: "-destroy"
    secrets:
      modernisation_platform_environments: "${{ secrets.MODERNISATION_PLATFORM_ENVIRONMENTS }}"
      pipeline_github_token: "${{ secrets.MODERNISATION_PLATFORM_CI_USER_ENVIRONMENTS_REPO_PAT }}"
