name: "RAM Share Association"

on:
  [repository_dispatch]

env:
  TF_IN_AUTOMATION: true

defaults:
  run:
    shell: bash

member-account-ram-associaton:
  runs-on: [ubuntu-latest]
  if: github.event.ref == 'refs/heads/main'
  steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
              - name: get changed files
      id: new_account
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r HEAD^..HEAD | awk '{print $1}' | grep "terraform/environments/*" |  cut -d/ -f3 | uniq | xargs)"
    - name: Set RAM assocation for member account
      run: |
        if [ ! -n ${{ steps.new_account.outputs.files }} ]
        then
        for i in ${{ steps.new_account.outputs.files }}
        do
        echo "[+] Setting up RAM asocation for ${i} environment: ${{ github.event.client_payload.text }}"
        bash scripts/member-account-ram-association.sh ${i} ${{ github.event.client_payload.text }}
        done
        else
        echo "[+] There were no new AWS member accounts to process"
        fi