---
name: xhibit-portal-prod-plan
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, reopened]
    paths:
      - 'terraform/environments/xhibit-portal/**'
      - '.github/workflows/xhibit-portal-prod.yml'
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_IN_AUTOMATION: true
defaults:
  run:
    shell: bash

jobs: 
  plan-production:
    name: Plan Production - xhibit-portal
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/xp-dev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
      - name: Load and Configure Terraform
        uses: hashicorp/setup-terraform@v1.3.2
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false
      - name: Terraform plan - production
        run: |
          echo "Terraform plan - ${TF_ENV}"
          bash scripts/terraform-init.sh terraform/environments/xhibit-portal
          terraform -chdir="terraform/environments/xhibit-portal" workspace select "xhibit-portal-${TF_ENV}"
          bash scripts/terraform-plan.sh terraform/environments/xhibit-portal
        env:
          TF_ENV: production
